# .streamlit/config.toml

[theme]
primaryColor = "#FF4500"  # Naranja rojo
backgroundColor = "#121212"  # Negro
secondaryBackgroundColor = "#282828"  # Gris oscuro
textColor = "#FFFFFF"  # Blanco
font = "sans serif"
